export const SPORTS = [
  {
    id: 'basketball',
    name: 'Basketball',
    tagline: 'Court Vision & Explosive Power',
    color: 0xe85d04,
    accentHex: '#e85d04',
    floorColor: 0x1a0e06,
    fogColor: 0x100800,
    modelPath: '/models/basketball.glb',
    bgPath: '/backgrounds/basketball.webp',
    ballColor: null,  // keep original colors
    stats: [
      { name: 'Sprint Speed',  value: '18.4', unit: 'mph', joint: 'foot' },
      { name: 'Vertical Jump', value: '34',   unit: 'in',  joint: 'hip'  },
      { name: 'Reaction Time', value: '0.21', unit: 's',   joint: 'head' },
      { name: 'Shot Arc',      value: '52',   unit: '°',   joint: 'hand' },
      { name: 'Lateral Speed', value: '12.1', unit: 'mph', joint: 'knee' },
    ],
  },
  {
    id: 'hockey',
    name: 'Ice Hockey',
    tagline: 'Edge Work & Shot Power',
    color: 0x4fc3f7,
    accentHex: '#4fc3f7',
    floorColor: 0x060d12,
    fogColor: 0x001520,
    modelPath: '/models/hockey.glb',
    bgPath: '/backgrounds/hockey.webp',
    ballColor: null,
    stats: [
      { name: 'Skating Speed', value: '23.2', unit: 'mph', joint: 'foot' },
      { name: 'Shot Power',    value: '94',   unit: 'mph', joint: 'hand' },
      { name: 'Reaction Time', value: '0.18', unit: 's',   joint: 'head' },
      { name: 'Edge Agility',  value: '9.2',  unit: 'pts', joint: 'knee' },
      { name: 'Puck Control',  value: '87',   unit: '%',   joint: 'hip'  },
    ],
  },
  {
    id: 'soccer',
    name: 'Soccer',
    tagline: 'Field Intelligence & Stamina',
    color: 0x4caf50,
    accentHex: '#4caf50',
    floorColor: 0x041006,
    fogColor: 0x011004,
    modelPath: '/models/soccer.glb',
    bgPath: '/backgrounds/football.webp',
    ballColor: null,
    stats: [
      { name: 'Sprint Speed',   value: '21.6', unit: 'mph', joint: 'foot' },
      { name: 'Reaction Time',  value: '0.19', unit: 's',   joint: 'head' },
      { name: 'Pass Accuracy',  value: '91',   unit: '%',   joint: 'hand' },
      { name: 'Stamina Index',  value: '94',   unit: 'pts', joint: 'hip'  },
      { name: 'Tactical Score', value: '88',   unit: 'pts', joint: 'knee' },
    ],
  },
  {
    id: 'baseball',
    name: 'Baseball',
    tagline: 'Mechanics & Exit Velocity',
    color: 0xffd54f,
    accentHex: '#ffd54f',
    floorColor: 0x100b02,
    fogColor: 0x120d00,
    modelPath: '/models/baseball.glb',
    bgPath: '/backgrounds/baseball.webp',
    ballColor: null,  // white baseball — original
    stats: [
      { name: 'Pitch Speed',   value: '94',   unit: 'mph', joint: 'hand' },
      { name: 'Swing Speed',   value: '82',   unit: 'mph', joint: 'hip'  },
      { name: 'Exit Velocity', value: '107',  unit: 'mph', joint: 'foot' },
      { name: 'Reaction Time', value: '0.22', unit: 's',   joint: 'head' },
      { name: 'Spin Rate',     value: '2340', unit: 'rpm', joint: 'knee' },
    ],
  },
  {
    id: 'fencing',
    name: 'Fencing',
    tagline: 'Precision, Speed & Tactics',
    color: 0xab47bc,
    accentHex: '#ab47bc',
    floorColor: 0x080010,
    fogColor: 0x060008,
    modelPath: '/models/fencing.glb',
    bgPath: '/backgrounds/fencing.webp',
    ballColor: null,
    stats: [
      { name: 'Attack Speed',   value: '2.1',  unit: 'm/s', joint: 'hand' },
      { name: 'Reaction Time',  value: '0.15', unit: 's',   joint: 'head' },
      { name: 'Footwork Speed', value: '14.8', unit: 'mph', joint: 'foot' },
      { name: 'Stamina',        value: '91',   unit: 'pts', joint: 'hip'  },
      { name: 'Tactical Score', value: '93',   unit: 'pts', joint: 'knee' },
    ],
  },
  {
    id: 'softball',
    name: 'Softball',
    tagline: 'Power Hitting & Field Range',
    color: 0xff7043,
    accentHex: '#ff7043',
    floorColor: 0x100502,
    fogColor: 0x0e0400,
    modelPath: '/models/softball.glb',   // same GLB as baseball
    bgPath: '/backgrounds/baseball.webp', // same stadium
    ballColor: '#c8e600',                // yellow-green softball
    stats: [
      { name: 'Pitch Speed',   value: '72',  unit: 'mph', joint: 'hand' },
      { name: 'Swing Speed',   value: '79',  unit: 'mph', joint: 'hip'  },
      { name: 'Exit Velocity', value: '98',  unit: 'mph', joint: 'foot' },
      { name: 'Reaction Time', value: '0.20', unit: 's',  joint: 'head' },
      { name: 'Field Range',   value: '96',  unit: 'pts', joint: 'knee' },
    ],
  },
]
